export const RP_OBSERVATION_LIST_PATH = '/rpobservationslist/'
export const RP_OBSERVATION_PATH = '/rpobservation/'
export const RP_OBSERVATION_SCREEN_PATH = '/rpobservationscreen/'
export const OBSERVATIONS_ASSIGNED_TO_RP = '/observationsassignedrp/'
export const OBSERVATION_SCREEN_PATH = '/observationscreen/'
