export const USER_OBSERVATION_LIST_PATH = '/userobservationslist/'
export const USER_OBSERVATION_PATH = '/userobservation/'
export const USER_OBSERVATION_SCREEN_PATH = '/observationscreen/'
export const RP_OBSERVATION_LIST_PATH = '/rpobservationslist/'
export const OBSERVATIONS_ASSIGNED_TO_RP = '/observationsassignedrp/'
export const LIST_OF_OBSERVATIONS_PATH = '/listofobservations/'